# Generated by Django 4.0.5 on 2022-07-07 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educationStructure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='educationStructure.country', verbose_name='Країна'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='educationStructure.city', verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='educationStructure.country', verbose_name='Країна'),
        ),
    ]
