# Generated by Django 4.0.5 on 2022-07-07 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educationStructure', '0002_alter_city_country_alter_institution_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='educationStructure.country', verbose_name='Країна'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Назва країни'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='educationStructure.city', verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='educationStructure.country', verbose_name='Країна'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(db_index=True, max_length=1024, verbose_name='Назва'),
        ),
    ]
