from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse


def student_index(request):
    return redirect('/student/1/dashboard')


def student_dashboard(request, sid):
    todayTimeTable = (
        {'id': 1,
         'lessonName': 'Англійська мова',
         'lessonStartTime': '08:30',
         'lessonEndTime': '09:15',
         'ended': True,
         'ordered': 1},
        {'id': 2,
         'lessonName': 'Фізкультура',
         'lessonStartTime': '09:25',
         'lessonEndTime': '10:10',
         'ended': True,
         'ordered': 2},
        {'id': 3,
         'lessonName': 'Математика',
         'lessonStartTime': '10:30',
         'lessonEndTime': '11:15',
         'ended': False,
         'ordered': 3},
        {'id': 4,
         'lessonName': 'Історія України',
         'lessonStartTime': '11:45',
         'lessonEndTime': '12:30',
         'ended': False,
         'ordered': 4},
        {'id': 5,
         'lessonName': 'Математика',
         'lessonStartTime': '12:45',
         'lessonEndTime': '13:30',
         'ended': False,
         'ordered': 5},
    )
    return render(request, 'studentDashboard.html', {'todayTimeTable': todayTimeTable})


def student_profile(request, sid):
    profileList = (
     dict(id=1, avatar='img/avatars/avatar1.jpeg', name='Руслан', surname='Токар', login='rexxx',
          email='djrexxx87@gmail.com'),
     dict(id=2, avatar='img/avatars/avatar1.jpeg', name='Олена', surname='Токар', login='olenaNech',
          email='djrexxx87@gmail.com'),
     dict(id=3, avatar='img/avatars/avatar1.jpeg', name='Назар', surname='Токар', login='NazarKarate',
          email='djrexxx87@gmail.com'),
     dict(id=4, avatar='img/avatars/avatar1.jpeg', name='Руслан', surname='Токар', login='rexxx',
          email='djrexxx87@gmail.com'),
     dict(id=5, avatar='img/avatars/avatar1.jpeg', name='Костянтин', surname='Чорняєв', login='Bonifacyi',
          email='djrexxx87@gmail.com'),
     dict(id=6, avatar='img/avatars/avatar1.jpeg', name='Руслан', surname='Токар', login='rexxx',
          email='djrexxx87@gmail.com'),
     dict(id=7, avatar='img/avatars/avatar1.jpeg', name='Руслан', surname='Токар', login='rexxx',
          email='djrexxx87@gmail.com'),
     dict(id=8, avatar='img/avatars/avatar1.jpeg', name='Руслан', surname='Токар', login='rexxx',
          email='djrexxx87@gmail.com'),
     dict(id=9, avatar='img/avatars/avatar1.jpeg', name='Руслан', surname='Токар', login='rexxx',
          email='djrexxx87@gmail.com'),
     dict(id=10, avatar='img/avatars/avatar1.jpeg', name='Руслан', surname='Токар', login='rexxx',
          email='djrexxx87@gmail.com'),
     dict(id=11, avatar='img/avatars/avatar1.jpeg', name='Руслан', surname='Токар', login='rexxx',
          email='djrexxx87@gmail.com'),
     dict(id=12, avatar='img/avatars/avatar1.jpeg', name='Руслан', surname='Токар', login='rexxx',
          email='djrexxx87@gmail.com')
    )

    return render(request, 'studentProfile.html')


def student_class(request, sid):
    studentList = (
        {'id': 1,
         'avatar': 'img/avatars/avatar1.jpeg',
         'name': 'Токар Руслан',
         'nickname': 'rexxx',
         'address': 'Kharkiv',
         'age': 18,
         'birthDate': '07.03.1987',
         'volume': 10.0},
        {'id': 2,
         'avatar': 'img/avatars/avatar2.jpeg',
         'name': 'Токар Олена',
         'nickname': 'olenaNech',
         'address': 'London',
         'age': 19,
         'birthDate': '08.03.1987',
         'volume': 11.0},
        {'id': 3,
         'avatar': 'img/avatars/avatar3.jpeg',
         'name': 'Токар Назар',
         'nickname': 'NazarKarate',
         'address': 'NewYork',
         'age': 20,
         'birthDate': '09.03.1987',
         'volume': 11.2},
        {'id': 4,
         'avatar': 'img/avatars/avatar4.jpeg',
         'name': 'Чорняєв Костянтин',
         'nickname': 'Bonifaciy',
         'address': 'San Francisco',
         'age': 21,
         'birthDate': '10.03.1987',
         'volume': 9.0},
        {'id': 5,
         'avatar': 'img/avatars/avatar5.jpeg',
         'name': 'Чорняєва Олена',
         'nickname': 'BonifaciyMom',
         'address': 'London',
         'age': 22,
         'birthDate': '11.03.1987',
         'volume': 11.0},
        {'id': 6,
         'avatar': 'img/avatars/avatar1.jpeg',
         'name': 'Чорняєв Сергій',
         'nickname': 'Serhio',
         'address': 'New York',
         'age': 23,
         'birthDate': '12.03.1987',
         'volume': 9.8},
        {'id': 7,
         'avatar': 'img/avatars/avatar2.jpeg',
         'name': 'Чорняєв Дмитро',
         'nickname': 'fetty',
         'address': 'Tokyo',
         'age': 24,
         'birthDate': '13.03.1987',
         'volume': 10.2},
        {'id': 8,
         'avatar': 'img/avatars/avatar3.jpeg',
         'name': 'Ситничук Аліна',
         'nickname': 'Alish',
         'address': 'San Francisco',
         'age': 25,
         'birthDate': '14.03.1987',
         'volume': 10.0},
        {'id': 9,
         'avatar': 'img/avatars/avatar4.jpeg',
         'name': 'Паніна Оксана',
         'nickname': 'PanPan',
         'address': 'London',
         'age': 26,
         'birthDate': '15.03.1987',
         'volume': 12.0},
        {'id': 10,
         'avatar': 'img/avatars/avatar5.jpeg',
         'name': 'Паніна Софія',
         'nickname': 'Sofya',
         'address': 'New York',
         'age': 27,
         'birthDate': '16.03.1987',
         'volume': 10.1},
        {'id': 11,
         'avatar': 'img/avatars/avatar1.jpeg',
         'name': 'Токар Наталія',
         'nickname': 'Mom',
         'address': 'Tokyo',
         'age': 28,
         'birthDate': '17.03.1987',
         'volume': 11.0},
        {'id': 12,
         'avatar': 'img/avatars/avatar2.jpeg',
         'name': 'Токар Анатолій',
         'nickname': 'Dad',
         'address': 'Tokyo',
         'age': 29,
         'birthDate': '18.03.1987',
         'volume': 11.0}
    )

    #studentList = studentList.order_by('name')
    return render(request, 'studentClas.html', {'studentList': studentList})


'''
def login(request):
    return render(request, 'login.html', {})
'''
